# Generated by Django 3.2.7 on 2023-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('oxygen', models.FloatField()),
                ('pressure', models.FloatField()),
                ('flow', models.FloatField()),
                ('co2', models.FloatField()),
                ('spo2', models.FloatField()),
                ('alarm', models.BooleanField(default=False)),
            ],
        ),
    ]
