# Generated by Django 5.1.4 on 2025-01-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_data', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_logs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_data', to='patients.patient'),
        ),
    ]
