# Generated by Django 4.2.1 on 2023-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosPrueba',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('dato1', models.CharField(max_length=50)),
                ('dato2', models.CharField(max_length=50)),
                ('dato3', models.CharField(max_length=50)),
                ('dato4', models.CharField(max_length=50)),
            ],
        ),
    ]
