# Generated by Django 4.2.1 on 2023-06-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametrosPrueba',
            new_name='ParametersTest',
        ),
        migrations.RenameField(
            model_name='parameterstest',
            old_name='dato1',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='parameterstest',
            old_name='dato2',
            new_name='data2',
        ),
        migrations.RenameField(
            model_name='parameterstest',
            old_name='dato3',
            new_name='data3',
        ),
        migrations.RenameField(
            model_name='parameterstest',
            old_name='dato4',
            new_name='data4',
        ),
        migrations.RenameField(
            model_name='parameterstest',
            old_name='id_parametro',
            new_name='id_param',
        ),
    ]
